/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandLogo: typeof import('./src/components/base/BrandLogo.vue')['default']
    EventsTab: typeof import('./src/components/PopupTabs/EventsTab.vue')['default']
    FriendPicture: typeof import('./src/components/PopupComponents/FriendPicture.vue')['default']
    GalleryTab: typeof import('./src/components/PopupTabs/GalleryTab.vue')['default']
    LocationBadges: typeof import('./src/components/base/LocationBadges.vue')['default']
    PersonalInfosTab: typeof import('./src/components/StandaloneTabs/PersonalInfosTab.vue')['default']
    PlayerModerationTab: typeof import('./src/components/StandaloneTabs/PlayerModerationTab.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    PresenceBadge: typeof import('./src/components/base/PresenceBadge.vue')['default']
    PreviousUserChanges: typeof import('./src/components/PopupTabs/EventsTab/PreviousUserChanges.vue')['default']
    RankBadge: typeof import('./src/components/base/RankBadge.vue')['default']
    SessionGate: typeof import('./src/components/base/SessionGate.vue')['default']
    SettingsTab: typeof import('./src/components/PopupTabs/SettingsTab.vue')['default']
    Standalone: typeof import('./src/components/Standalone.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UEmpty: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Empty.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UserAvatar: typeof import('./src/components/base/UserAvatar.vue')['default']
    UserDetails: typeof import('./src/components/UserDetails.vue')['default']
    WorldsTab: typeof import('./src/components/PopupTabs/WorldsTab.vue')['default']
  }
}
